name: CI

on: [issues]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      env: 
        super_secret: ${{ secrets.SuperSecret }}
      run: |
        echo Add other actions to build,
        env
